### PR TITLE
add json support for defs

### PR DESCRIPTION
**Pull request by btpoe**
It would be great to add json support to the def files. That way you can nest/namespace your def includes instead of having to work with a flat stack.

If you need me to elaborate on it's usefulness, let me know.

### CODE REVIEW

**Comment by zlumer** [comment]
For a non-maintainer this looks interesting, but I'm not sure I fully understand what it does. Can you please give an example?

**Comment by btpoe** [comment]
For sure. In my case, I'm using doT for HTML emails and I find myself using a few table helpers often.

Here's my `_table.def.json` file I have for the table helpers:
```javascript
{
  "_base": "border=\"0\" cellpadding=\"0\" cellspacing=\"0\"",
  "_root": "width=\"640\" {{#def._table._base}}",
  "_fill": "width=\"100%\" {{#def._table._base}}",
  "_copy": "width=\"85%\" {{#def._table._base}}",
  "body": "<!--[if gte mso 9]><table width=\"100%\" {{#def._table._base}}><tr><td align=\"center\"><table width=\"640\" {{#def._table._base}}><tr><td><![endif]-->",
  "bodyEnd": "<!--[if gte mso 9]></td></tr></table></td></tr></table><![endif]-->",
  "break": "<tr><td height=\"20\" style=\"height: 20px; line-height: 20px;\">&nbsp;</td></tr>",
  "breakDouble": "<tr><td height=\"40\" style=\"height: 40px; line-height: 40px;\">&nbsp;</td></tr>"
}
```

This mod treats any `.def.json` files the same as a `.def` file with the extra step of running the contents through `JSON.parse`.

**Comment by zlumer** [comment]
Looks awesome! Thanks, I will try that in my workflow.

**Comment by epoberezkin** [comment]
@btpoe doT already supports definitions inside .def files using more convenient syntax than this - you can have HTML with line breaks. So all your defs can be in a single file like this:

```
{{##def.table_base: border="0" cellpadding="0" cellspacing="0" #}}
{{##def.table_root: width="640" {{#def.table_base}} #}}

{{##def.table_body:
  <!--[if gte mso 9]>
    <table width="100%" {{#def.table_base}}>
      <tr>
        <td align="center">
          <table width="640" {{#def.table_base}}>
            <tr>
              <td>
  <![endif]-->
#}}

{{##def.table_bodyEnd:
  <!--[if gte mso 9]>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  <![endif]-->
#}}
```

Although it does not support name-spacing, you still can have longer names separating namespace with "_" (like I did in the example).

To me it seems more readable than cramming HTML into strings where you have no indentation and need to escape (and using templates is actually aims to avoid exactly that).

**Comment by epoberezkin** [comment]
@btpoe closing - it is out of date, also seems unnecessary. See above

**Pull request closed without merging**
