### PR TITLE
Object iterators added.

### PR DESCRIPTION
**Pull request by milichev**
Added support of object property iterators, e.g. `for (key in obj) {...}`

Notation is similar to array iterators, '@' char is used instead of '~':

``` javascript
{{@ {one: 1, two: 2, three: 3} :val :key}}
    {{=key}} = {{=val}}
{{@}}
```

Also, this can iterate only own properties – with additional '@':

``` javascript
{{ obj = (function() {
    function O() {
        this.four = 4;
    }
    O.prototype = { one: 1, two: 2, three: 3 };
    return new O;
})(); }}

{{@@ obj :val :key}}
    {{=key}} = {{=val}}
{{@@}}
```

### CODE REVIEW

**Comment by klimashkin** [comment]
+1

**Comment by VitalyKovalev** [comment]
same q to @olando, do you support this project?

**Comment by zevero** [comment]
please pull!
It may be easier without the @.
Just using ~ and check for object...

Is there a case, where you would like to iterate without checking for own properties?

Please pull!!!

**Comment by mirrr** [comment]
:+1:

**Comment by epoberezkin** [comment]
:+1:

**Comment by amigolargo** [comment]
+1

**Comment by epoberezkin** [comment]
@milichev see https://github.com/olado/doT/pull/124#issuecomment-257169745

**Pull request closed without merging**
