### PR TITLE
Enhancement proposal: destructuring args declaration

### PR DESCRIPTION
**Pull request by complyue**
I find doT quite elegant and lean :thumbsup:, lovin it.

And I propose the enhancement conveyed in this PR, it seems to be competing with #266 (and #29 for the non-nesting case) to address the wondering raised by #214 (with my +1 to it).

This PR introduces a new `args` templateSettitng, which defines a delimiter (`{{@ }}` by default) allowed at the very beginning of a template, to declare interesting variable names out of the single `it` object, then with such a declaration present, the mentioned variables are used without prefix throughout the template. Note that with presence of such a declaration, `templateSettings.varname` will be ignored in processing of the template instance, thus `it` or another name will NOT be available to the template. Templates without the `{{@ }}` declaration will maintain old behaviour intact so it'll be automatically backward compatible.

I think the test demonstrates it well enough:
```python
		test([
			'{{@one,two}}{{=one}}{{=two}}',
			'{{@one,two}}{{= one}}{{= two}}',
			'{{@one,two}}{{= one }}{{= two }}'
		], {one:1, two: 2}, '12');
		test([
			'{{@ one, two=2 }}{{=one}}{{=two}}',
		], {one:1}, '12');
```

The implementation leverages es6 [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) to selectively accept arguments from `it` (with default value spec, feel like an extra bonus :smiley:), I feel it sensible at language level, and shouldn't incur unreasonable performance penalty tho I'm not experienced enough with doT to play with the benchmarks.

@epoberezkin @olado @1mike12

### CODE REVIEW

**Comment by epoberezkin** [comment]
@complyue thank you for the PR.

The main idea of doT is to allow any JS in the template so what you propose can already be achieved with `{{ const {one, two} = it; }}`, provided your current JS environment supports destructuring, otherwise you can achieve the same with two assignments.

So it doesn’t really seem necessary to have any special syntax for what’s already possible.

**Comment by complyue** [comment]
@epoberezkin you're right. but I'd think this can make possible for the unnecessary variable `it` from appearing, so the templating paradigm can be a bit more declarative than imperative.

I'm currently using doT to update many small pieces of html contents, such as `href` of `<a/>`, text of short `<span/>` etc. and no data is being `iterated`, so I'd prefer `data` over `it`. but writing `http://xxx.info/{{=data.symbol}}` feels some how like embedding assembly code. tho I admit `{{@symbol}}http://xxx.info/{{=symbol}}` feels rather overkilling. but `{{const {symbol} = data; }}http://xxx.info/{{=symbol}}` feels much worse.

may be I can finally train my brain to recognise `it.` without other sensation.

doT is amazing any way, thanks for the perfect work!

**Comment by epoberezkin** [comment]
So, possibly it could be just an option passed to doT.template to define property names that will be included as variables. Using template instruction seems messy, as they can be in the middle, repeated etc.

**Comment by epoberezkin** [comment]
in v2 as `argName: string[]` option

**Pull request closed without merging**
