### PR TITLE
Adds an engine attribute for easy identification

### PR DESCRIPTION
**Pull request by designfrontier**
I am working on an application server and the ability to identify
and handle various templating engines is important. Right now we
are handling detection of doT by looking at the shape of the
template engine. Would be nice to have a single field to check like
handlebars has, for instance.

This adds an engine attribute so that it will be easy to detect in
the future.

### CODE REVIEW

**Comment by epoberezkin** [comment]
@designfrontier can't hurt I guess...  are you going to suggest the same to others I assume? Can you  please post the list of engines that support it already (or links to PRs).

**Comment by designfrontier** [comment]
PR in jade/Pug: https://github.com/pugjs/pug/pull/2630

working on getting them open for others. Handlebars, underscore and lodash are
all detectable by `.name` or `constructor.name` currently.

**Comment by designfrontier** [comment]
ejs: https://github.com/mde/ejs/pull/220

**Comment by designfrontier** [comment]
as a further point of information ejs merged their pull request for this yesterday evening and it will be going out in their next release

**Comment by designfrontier** [comment]
@epoberezkin would love to get this merged since pug and ejs have merged theirs now. If you have any questions or would like more info let me know

**Comment by epoberezkin** [comment]
@designfrontier thank you

**Pull request merged**
