### PR TITLE
More stripping rules

### PR DESCRIPTION
**Pull request by IvanDimanov**
Hi Laura,
  First of all I'd like to Thank You for the great template engine you've made, using it for some time and feeling quite comfortable with it.

  I've noticed that HTML comments and spaces between tags are not been removed even with 'strip:true' property.
  That's why I think the update I made could be useful for others too.

Bests,
Ivan

### CODE REVIEW

**Comment by JesseFarebro** [comment]
I'd hopefully still like to see this merged!

:+1:

**Comment by epoberezkin** [comment]
Removing browser comments is definitely out of scope as they can be interpreted by browsers and by ESI servers.

**Comment by IvanDimanov** [comment]
@epoberezkin Can we have it as separate feature `-strip-comments`

**Comment by epoberezkin** [comment]
As I wrote it is also out of scope. doT core should not rely on any target language semantics because:
1. doT can be (and is) used not only for HTML rendering - it can be JSON, JavsScript, etc.
2. there are other tools that can strip comments that you need to
3. you can always replace HTML comments with doT comments (`{{ /* ... */ }}`) that would not be in HTML.

So I don't see why it should be added.
Other stripping changes this PR adds need additional tests and probably can only be added in the next major version. Also there are several other proposed changes related to whitespace stripping.

I think we should be very careful in changing whitespace stripping rules - the change may solve the problems of a few users and create problems for 100s of other users.

**Comment by IvanDimanov** [comment]
ok, thank you for your answer

**Pull request closed without merging**
